language: node_js
node_js:
  - '6'
install:
  - npm install -g codecov nyc npx
  - npm install

script:
  - npm run lint
  - npm test

after_success:
  - npm run report-coverage
  - npx -p node@8 -c "npm run semantic-release"